### ISSUE TITLE
What is the Mac OS-X equivalent command for xdg-open

### ISSUE THREAD

**Issue by rambalachandran** [egh/zotxt-emacs#1]
The README states that in order that  

> to ensure that zotero: links are followed by xdg-open, the default browser called by emacs, you may need to run the following command:

`xdg-mime default firefox.desktop x-scheme-handler/zotero`

What is the equivalent command that I need to run in terminal in case of Mac OS-X?

**Comment by egh** [comment]
Presumable `open`?
