### ISSUE TITLE
invalid function (mk (point-marker))

### ISSUE THREAD

**Issue by junfx** [egh/zotxt-emacs#10]
When I C-c " i, emacs always display "_invalid function: (mk (point-marker))_" in mini-buffer.
I tried:
- in an empty org file
- remove all packages in elpa, and reinstall zotxt from emacs package system
- emacs24.5 on win10
- emacs24.5 on fedora

version: zotxt-20160427.1922 from melpa.org
code in org-zotxt.el:
```
  (interactive "P")
  (lexical-let ((mk (point-marker)))
    (deferred:$
      (if (equal '(4) arg)
```
Has anyone else encountered this type of error?

**Comment by egh** [comment]
My mistake. I forgot to `(require 'cl)` at compile time. Should be fixed soon in the MELPA unstable release. Thank you for the report!

**Comment by egh** [comment]
Works for me with the new version, running from a clean install of emacs.

Thanks for the report, and apologies! `cl` is always tricky because many of the packages I use require it.
