### ISSUE TITLE
Error when displaying PDF

### ISSUE THREAD

**Issue by AprilAppleAnnA** [egh/zotxt-emacs#11]
Hi Erik,

When I inserted the link of paper through "C-c " i", the program generated link [zotero://select/items/0_G9VMAV5Z] successfully. However, when I clicked the link, the computer gives me an error that "REQUEST [error] Eroor (error) while connecting to the hettp://127.0.01:23119/zotxt/select". Could you give me some suggestions on fixing this error? Thank you very much!

I followed the installation instruction on http://www.mkbehr.com/posts/a-research-workflow-with-zotero-and-org-mode/.

**Comment by egh** [comment]
Thank you for the report!

That is strange. Is zotero still running when you click on the link? It won't launch zotero or firefox if it is not running.

**Comment by Eva2017** [comment]
Hi Erik,
Thank you for reply. I did open my standalone zotero, and I think it is the zetero API is not working appropriately to create the http://127.0.01:23119/zotxt/select.

**Comment by egh** [comment]
Thanks again! I'm having a hard time reproducing this locally. Can you let me know what version of emacs and zotero you are using? If you are using Zotero 5 beta, I'm hoping to support that soon, but it isn't working yet.

**Comment by egh** [comment]
I should say right now that zotxt only works with the org mode from ELPA (version > 9). I'm working on ensuring it works with older org modes right now.

**Comment by egh** [comment]
The zotxt-emacs tests are now passing for the org-mode built in to emacs. This may fix your issue - you will need to update zotxt from MELPA.
