### ISSUE TITLE
Store zotero link in property when using org-noter

### ISSUE THREAD

**Issue by et2010** [egh/zotxt-emacs#14]
Hello,

Thanks for this wonderful package! zotxt-emacs works great. I want to try this experimental feature, but bump into an error:

```
deferred error : (wrong-type-argument listp "[
  {
    \"key\": \"1_9XES333X\",
    \"paths\": [
      \"/home/jw/Zotero/storage/APGFF82R/14680629.2013.html\"
    ]
  }
]")
```

**Comment by egh** [comment]
Oh, I'm sorry! I somehow forgot to commit an essential piece. It should be fixed now with https://github.com/egh/zotxt-emacs/commit/23a4a9f74a658222027d53a9a83cd4bcc583ca8b

**Comment by et2010** [comment]
Thanks for the fix! It works like a charm! 

I also want to insert a zotero link in the property drawer. I modifed the noter function and insert a link, It works but the link description is not citation. How could I use citation as link description?

**Comment by egh** [comment]
@et2010 Can you show what you'd like the entry to look like? I'm sure we can improve this feature - I haven't really used it, I just created it as an experiment.

**Comment by et2010** [comment]
What it looks like now:
```
* A NOTE
:PROPERTIES:
:NOTER_DOCUMENT: ../../../Zotero/storage/GXXCQ6J8/mydoc.pdf
:ZOTERO_LINK: [[zotero://select/items/1_A68STSTM]]
:END:
```

The desired entry looks like:
```
* A NOTE
:PROPERTIES:
:NOTER_DOCUMENT: ../../../Zotero/storage/GXXCQ6J8/mydoc.pdf
:ZOTERO_LINK: [[zotero://select/items/1_A68STSTM][Alibali, M. W. (1999). How children change their minds: Strategy change can be gradual or abrupt. Developmental Psychology, 35, 127-145.]]
:END:
```

How can I get the description into the link?

**Comment by egh** [comment]
@et2010 That looks reasonable. I'll see what I can do.
