### ISSUE TITLE
Can't find items file

### ISSUE THREAD

**Issue by ransomts** [egh/zotxt-emacs#15]
Hi, I'm trying to set up zotxt on my machine, I've gotten zotxt-emacs from the git repo and release 5.0.2 zotxt installed on the standalone zotero. When I run `org-zotxt-insert-reference-link` the list of files pops up fine in helm, but when I select one emacs spits out this error message:

```REQUEST [error] Error (error) while connecting to http://127.0.0.1:23119/zotxt/items.```

When I cracked open the console and enabled logging in zotero, this seems to be the only major issue I saw, followed by listing out a bunch of files in my system.

```(5)(+0000004): HTTP/1.0 500 Internal Server Error X-Zotero-Version: 5.0.48 X-Zotero-Connector-API-Version: 2 Content-Type: text/plain; charset=UTF-8 csl is nullTypeError: csl is null ```

Did I miss a step, or is this a bug? This looks very helpful to my workflow and I'd like to use it

**Comment by ransomts** [comment]
Thank you! If you need me to collect logs or something just let me know.

**Comment by egh** [comment]
Sorry, I'm cleaning out old bugs. Is this still an issue?

**Comment by ransomts** [comment]
Looks like it's been resolved. Got it installed and working just now.

**Comment by egh** [comment]
Great, thank you!
