### ISSUE TITLE
`Invalid function: (mk (point-marker))`

### ISSUE THREAD

**Issue by pierwill** [egh/zotxt-emacs#18]
I'm glad this is back after it was gone for a while with Zotero 5!

-----

I'm getting `org-zotxt-insert-reference-link: Invalid function: (mk (point-marker))`...

I switched over to Cask for emacs packages recently, so I'll check things out there... but any pointers on this error message would be great.

**Comment by egh** [comment]
This should be inside a `lexical-let` and is basically a let binding. Can you let me know what emacs version and platform you are on? Thanks!

**Comment by pierwill** [comment]
Emacs 26.1 via homebrew on os x.

Org-mode version 9.1.14

**Comment by egh** [comment]
Strange, I can't replicate this with emacs 25 or 27 on linux. It might have something to do with cask - I've never used cask to manage my emacs packages, though the zotxt-emacs tests do use them, so I'm not sure why it wouldn't work.

**Comment by DesiQuintans** [comment]
I briefly had this problem but simply ran `M-x package-reinstall` to get the newest version on MELPA.

**Comment by Zreshamwala** [comment]
Also experiencing this issue. 

I am running GNU Emacs 26.1 on Windows 10
Org-mode Version 9.1.9

Unlike *pierwill*, not using cask.

M-x package-reinstall did not resolve it.

**Comment by egh** [comment]
@Zreshamwala I'd really like to fix this but I'm not sure what is going on. I *think* the problem is that somehow `cl` is not being loaded properly or there is something wrong with your `elc` files. The closest error I can find on the internet is here: https://github.com/Sarcasm/flycheck-irony/issues/7

Can you try to reproduce using `emacs -q` (see https://www.gnu.org/software/emacs/manual/html_node/emacs/Understanding-Bug-Reporting.html#Understanding-Bug-Reporting) ? That might help. Thank you!

**Comment by mjj55409** [comment]
I just ran into the same issue.

Emacs 26.2
Ubuntu 18.04
Zotero 5.0.74

**Comment by Viehzeug** [comment]
I have the same issue on Emacs 26.2 on macOS 10.15.1.
The re-installation trick did not work for me.
I ran it twice with `-q`. First with my standard `.emacs.d.` folder and once with a competently clean `.emacs.d` folder.
On my Ubuntu machine (which uses the same config files) it works flawlessly.

**My `.emacs.d`**

```
emacs-26.2 -q
M-x package-initialize
C-x C-f /tmp/foo.org
M-x org-zotxt-mode
C-c " i
```
Here is the content of the message buffer:

```
For information about GNU Emacs and the GNU system, type C-h C-a.
You can run the command ‘package-initialize’ with M-x p-ini RET
delete-backward-char: Text is read-only
(New file)
Making completion list...
Created zotero link.
Org-Zotxt mode enabled in current buffer
org-zotxt-insert-reference-link: Invalid function: (mk (point-marker))
Quit
```
**Completely clean config**

```
M-x eval-expression (setq package-archives '(("gnu" . "https://elpa.gnu.org/packages/")
("melpa-stable" . "https://stable.melpa.org/packages/")))
M-x package-initialize
M-x package-refresh-contents
M-x package-install zotxt
C-x C-f /tmp/foo.org
M-x org-zotxt-mode
C-c " i
```

And the Message buffer:
```
Generating autoloads for zotxt-pkg.el...done
Generating autoloads for zotxt.el...done
Wrote /Users/marc/.emacs.d/elpa/zotxt-0.1.34/zotxt-autoloads.el [2 times]
Checking /Users/marc/.emacs.d/elpa/zotxt-0.1.34...
Compiling /Users/marc/.emacs.d/elpa/zotxt-0.1.34/org-zotxt.el...done
Wrote /Users/marc/.emacs.d/elpa/zotxt-0.1.34/org-zotxt.elc
Checking /Users/marc/.emacs.d/elpa/zotxt-0.1.34... [3 times]
Compiling /Users/marc/.emacs.d/elpa/zotxt-0.1.34/zotxt.el...done
Wrote /Users/marc/.emacs.d/elpa/zotxt-0.1.34/zotxt.elc
Checking /Users/marc/.emacs.d/elpa/zotxt-0.1.34...
Done (Total of 2 files compiled, 2 skipped)
(New file)
Making completion list...
Created zotero link.
Org-Zotxt mode enabled in current buffer
org-zotxt-insert-reference-link: Invalid function: (mk (point-marker)
```

**Comment by egh** [comment]
@Viehzeug Thank you so much for the details!! Iwill have to find a Mac to figure out how to fix this.

**Comment by egh** [comment]
Thanks again for the careful reproduction steps. I was able to reproduce this using melpa stable and windows. The version in melpa stable was quite old (Sorry!). I tagged a new release, and, after upgrading, the issue is fixed! Thanks again for the report and to @Viehzeug for the reproduction steps.
