### ISSUE TITLE
REQUEST error while trying to insert zotero link

### ISSUE THREAD

**Issue by rambalachandran** [egh/zotxt-emacs#2]
I installed zotxt from MEPLA. Added `(require 'zotxt)` in my `~/.emacs` file. When i enable 
`M-x org-zotxt-mode `
and type` C-c " i`, it opens a query where if I type an author name, it throws me an error

`REQUEST [error] Error (error) while connecting to http://127.0.0.1:23119/zotxt/search.`

I'm not sure as to what is the cause of the error and how to fix it to make emacs know about the zotero library.

**Comment by rambalachandran** [comment]
Ok this was silly. I never installed zotxt in Firefox. Upon installation, it works well. You can close the issue

**Comment by egh** [comment]
Great! Glad that was resolved.

**Comment by rambalachandran** [comment]
Unfortunately the issue is resurfacing again. This time the Zotxt is installed in Firefox and open and I'm not sure why

**Comment by egh** [comment]
Can you tell me what platform this is? Mac, Linux? I assume that you installed Zotxt via the mozilla addons page and it is up to date?

**Comment by rambalachandran** [comment]
Yes I did install Zotxt via firefox Addon. It is in Mac Yosemite. I removed it and reinstalled it and it works, but I dont know what made it work.

**Comment by egh** [comment]
That is odd. Firefox should need a restart before zotxt will work, but that should only be a problem once.
