### ISSUE TITLE
request-deferred and deferred names changed

### ISSUE THREAD

**Issue by millarc** [egh/zotxt-emacs#20]
A couple of days ago I downloaded Zotero,-5.0.77 the Firefox browser plugin, tzotxt-5.0.3.xpi plugin and finally zotxt-emacs from this site. By the way, Debian testing, with GNU Emacs 27.0.50 (build 108, x86_64-pc-linux-gnu, GTK+ Version 3.24.12) of 2019-10-19, org Org mode version 9.2.6 (release_9.2.6-559-ga01a8f @ /usr/local/share/org-mode/lisp/)
Apparently sometime during the past couple of years, I guess, the names for two of the required emacs packages - request-deferred and deferred - have been changed to emacs-request and emacs-deferred.
I finally had my org files up and running with org-zotxt-mode after I "cp -r ./emacs-request request-deferred" and "cp -r ./-emacs-deferred deferred"
Should the code in zotxt-emacs/org-zotxt.el and zotxt-emacs/zotxt.el require these packages by their new names and at the same time allow for the older names?
On the other hand, was I expected to know enough to change emacs-request to request-deferred, etc?

**Comment by egh** [comment]
@millarc I'm sorry you had this issue. The package names on MELPA are still `request-deferred` (http://melpa.org/#/request-deferred) and `deferred` (http://melpa.org/#/deferred) as far as I can see. How are you installing your packages?

**Comment by millarc** [comment]
I don't use MELPA (perhaps I should.)
I cloned them from https://github.com/tkf/emacs-request and https://github.com/kiwanami/emacs-deferred
Thank you for developing emacs-zotxt - it fits my needs.
Charlie Millar

**Comment by egh** [comment]
Glad to help! The `.el` file is still named `request-deferred.el` and `deferred.el`, so I think the code that calls `(require 'request-deferred)` is still correct. I can update the README to point to the required libraries for people who do not use MELPA.
