### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by pbienst** [egh/zotxt-emacs#26]
After playing around a bit with Zotero and zotxt-emacs, which mostly worked, I decided to start for real from scratch, with a new account and an empty slate.

This time however, whenever I want to insert the currently selected paper from Zotero, I get

```
Contacting host: 127.0.0.1:23119
[warn] request--url-retrieve-callback: (error http 404)
[error] request--callback: peculiar error: 404
[error] request-default-error-callback: http://127.0.0.1:23119/zotxt/items parse-error
``` 

One this which is different from my previous install is that installed the zotfile plugin, but I doubt this has an effect.

Just like before, I did use the (setq request-backend 'url-retrieve) option.

**Comment by egh** [comment]
Thanks for the report! If possible, can you enable Zotero debugging (https://www.zotero.org/support/debug_output) and attach the output? Thank you!

**Comment by pbienst** [comment]
Rebooting seems to have solved this problem, sorry for the spam :-)
