### ISSUE TITLE
Numbers instead of punctuation

### ISSUE THREAD

**Issue by cjpoor** [egh/zotxt-emacs#4]
Hi Erik,
Thanks for writing the plugin. I have been trying to make use of it and seem to be having some success. However, there is some odd behaviour with punctuation and diacritics. Here is one example:
﻿The inserted reference reads like this:
Ellerman, David. \342\200\234Autonomy in Education and Development.\342\200\235 Journal of International Co-operation in Education 7, no. 1 (2004): 3\342\200\22314.
I got similar results when a name in the reference contained a diacritic.
I doubt if I can just replace these numbers with what should be there and hope they will scan OK.
Do you have any suggestions?
Chris.

**Comment by cjpoor** [comment]
Sorry. The instruction in emacs when I exit - to encode as raw text - works.
Thanks again.
Chris.

**Comment by egh** [comment]
@cjpoor I'll look into the issue anyhow, because I don't think that is really ideal behavior.

**Comment by cjpoor** [comment]
There is another issue (or two) that may be related. For the last couple of days I have been getting an error on emacs initialization: Spacemacs encountered an error while loading your `/Users/christopherpoor/.spacemacs' file. Then zotxt is not available and the only way I have been able to get it back is by deleting my elpa folder and reinstalling it.
Putting the script

;; Activate org-zotxt-mode in org-mode buffers
(add-hook 'org-mode-hook (lambda () (org-zotxt-mode 1)))
;; Bind something to replace the awkward C-u C-c " i

(define-key org-mode-map
  (kbd "C-c \" \"") (lambda () (interactive)
                      (org-zotxt-insert-reference-link '(4))))

back in my .spacemacs user initialization didn't do it.
From googling this issue it seems very unpredictable but many seem to think it is related to problems in MELPA. I stripped back the .spacemacs to original and that didn't help.
I'm on Mac OS X 10.10.5 running emacs 24.5.1 and spacemacs 0.105.14

**Comment by cjpoor** [comment]
I loaded a new .spacemacs from template and do not get the initialization error now.

**Comment by cjpoor** [comment]
NJBS on gitter fixed my .spacemacs for me, but when I uncommented org and did <SPC f e R> I got a message saying 
symbol's function definition is void: org-zotxt-mode

**Comment by cjpoor** [comment]
Should this be in my .spacemacs?

(require 'org)
;; Activate org-zotxt-mode in org-mode buffers
(add-hook 'org-mode-hook (lambda () (org-zotxt-mode 1)))
;; Bind something to replace the awkward C-u C-c " i

(define-key org-mode-map
  (kbd "C-c \" \"") (lambda () (interactive)
                      (org-zotxt-insert-reference-link '(4))))

**Comment by cjpoor** [comment]
I did not have org installed - sorry.
Such a noob.

**Comment by cjpoor** [comment]
OK. org-zotxt-mode working again but still give the numbers instead of punctuation. Do I need to change my default font?

**Comment by cjpoor** [comment]
For some reason I have to keep on reinstalling zotxt

**Comment by cjpoor** [comment]
The compile does not seem to complete:
**********************************************
Leaving directory `/Users/christopherpoor/.emacs.d/elpa/request-20160108.33'

Compiling file /Users/christopherpoor/.emacs.d/elpa/request-20160108.33/request-autoloads.el at Mon Mar 14 16:19:31 2016
Entering directory `/Users/christopherpoor/.emacs.d/elpa/request-20160108.33/'

Compiling file /Users/christopherpoor/.emacs.d/elpa/request-20160108.33/request-pkg.el at Mon Mar 14 16:19:31 2016

Compiling file /Users/christopherpoor/.emacs.d/elpa/request-20160108.33/request.el at Mon Mar 14 16:19:31 2016

Compiling no file at Mon Mar 14 16:19:33 2016
Leaving directory `/Users/christopherpoor/.emacs.d/elpa/deferred-20160109.2046'

Compiling file /Users/christopherpoor/.emacs.d/elpa/deferred-20160109.2046/deferred-autoloads.el at Mon Mar 14 16:19:33 2016
Entering directory `/Users/christopherpoor/.emacs.d/elpa/deferred-20160109.2046/'

Compiling file /Users/christopherpoor/.emacs.d/elpa/deferred-20160109.2046/deferred-pkg.el at Mon Mar 14 16:19:33 2016

Compiling file /Users/christopherpoor/.emacs.d/elpa/deferred-20160109.2046/deferred.el at Mon Mar 14 16:19:33 2016
deferred.el:69:1:Warning: cl package required at runtime

In deferred:exec-task:
deferred.el:356:35:Warning: reference to free variable `deferred:onerror'

In deferred:earlier-main:
deferred.el:680:40:Warning: value returned from (length (symbol-value G90245))
    is unused
deferred.el:680:40:Warning: value returned from (symbol-value G90247) is
    unused

In end of data:
deferred.el:965:1:Warning: the following functions are not known to be defined:
    deferred:url-param-serialize, deferred:url-escape

Compiling no file at Mon Mar 14 16:19:35 2016
Leaving directory `/Users/christopherpoor/.emacs.d/elpa/request-deferred-20130526.1015'

Compiling file /Users/christopherpoor/.emacs.d/elpa/request-deferred-20130526.1015/request-deferred-autoloads.el at Mon Mar 14 16:19:36 2016
Entering directory `/Users/christopherpoor/.emacs.d/elpa/request-deferred-20130526.1015/'

Compiling file /Users/christopherpoor/.emacs.d/elpa/request-deferred-20130526.1015/request-deferred-pkg.el at Mon Mar 14 16:19:36 2016

Compiling file /Users/christopherpoor/.emacs.d/elpa/request-deferred-20130526.1015/request-deferred.el at Mon Mar 14 16:19:36 2016

Compiling no file at Mon Mar 14 16:19:37 2016
Leaving directory `/Users/christopherpoor/.emacs.d/elpa/zotxt-20151031.959'

Compiling file /Users/christopherpoor/.emacs.d/elpa/zotxt-20151031.959/org-zotxt.el at Mon Mar 14 16:19:37 2016
Entering directory `/Users/christopherpoor/.emacs.d/elpa/zotxt-20151031.959/'

Compiling file /Users/christopherpoor/.emacs.d/elpa/zotxt-20151031.959/zotxt-autoloads.el at Mon Mar 14 16:19:38 2016

Compiling file /Users/christopherpoor/.emacs.d/elpa/zotxt-20151031.959/zotxt-pkg.el at Mon Mar 14 16:19:38 2016

Compiling file /Users/christopherpoor/.emacs.d/elpa/zotxt-20151031.959/zotxt.el at Mon Mar 14 16:19:38 2016

**Comment by cjpoor** [comment]
Added  (require ‘cl-lib) to .spacemacs
zotxt seems to persist now.

However numbers still appear. Emacs asks me to code these as raw text when saving file.
When this is done, and file is closed and reopened, the numbers disappear.
But, in the last attempt, with two references together, the result was odd:

[[zotero://select/items/0_5H64ZGA8][Hermeling, Susanne. “Bildung-The Freedom of the Educated.” Journal of Adult and Continuing Education 9, no. 2 (2003): 167–81.[[zotero://select/items/0_857S4B8X][Adorno, Theodor W. Theorie der Halbbildung. 1st ed. Frankfurt am Main: Suhrkamp Verlag, 2006.]]]]

In the above, the section from “, Susanne .. “ thru “-81” is not underlined (linked), whereas in previous cases the entire reference remained as link after going through the save, mark as raw text, reopen process.

**Comment by cjpoor** [comment]
Sorry to display my ignorance again, but I can't figure out how and where I should run
xdg-mime default firefox.desktop x-scheme-handler/zotero

**Comment by egh** [comment]
@cjpoor I've pushed up a fix for the encoding issue. I'm not sure when/how this happened (it used to work), but it should be fixed.

**Comment by egh** [comment]
You should be able to install a new version from melpa in a little bit.

**Comment by egh** [comment]
You may or may not need to run ` xdg-mime default firefox.desktop x-scheme-handler/zotero` - in fact, I think you shouldn't. In any case, that is a linux only command. I am deleting that from the README. It should be possible to follow the links in the usual way in Org.

**Comment by cjpoor** [comment]
Many thanks.
I'll test it and get back to you.
