### ISSUE TITLE
org-zotxt-open-attachment prompts `file:` input 

### ISSUE THREAD

**Issue by Sepulta** [egh/zotxt-emacs#46]
Hello,

Just recently installed the Zotxt (5.1.0) and zotxt-emacs (5.0.5) plugins on my Linux machine, and was playing with `org-zotxt-insert-reference-link` and then opening those links again. I noticed that when I try to open some of the links (cursor on that link, opening with `C-c " a`) don't open that file, but rather it opens a prompt for inputting a filename in the minibuffer.

I haven't exactly pinpointed the difference in files/zotero entries between those that work and those that don't. Any suggestions to find out more?

**Comment by egh** [comment]
If there are multiple attachments for the item, you will be prompted for which to open. There should be completion for the file name. I think that is probably what is happening here.
