### ISSUE TITLE
inserting currently selected item from zotero?

### ISSUE THREAD

**Issue by pbienst** [egh/zotxt-emacs#48]
I had this command in my init to insert the currently selected item from zotero:

```
(define-key org-mode-map
  (kbd "C-c \" \"") (lambda () (interactive)
                  (org-zotxt-insert-reference-link '(4))))
```
However, after upgrading to the latest version, this no longer works and I'm prompted for a search field.

How do I update this to gain access to the previous functionality?

**Comment by egh** [comment]
Strange, probably a recent bug. Thanks for the report, I'll take a look.

**Comment by egh** [comment]
When I use `C-u C-c " i`, this works for me. I don't understand prefix args well enough, but this also works:

```
(define-key org-mode-map
  (kbd "C-c \" \"") (lambda () (interactive)
                      (execute-extended-command 4 "org-zotxt-insert-reference-link")))
```

I think I changed something recently with prefix args, so that presumably broke this.

**Comment by pbienst** [comment]
Thanks, that does the job!
