### ISSUE TITLE
Duplicate items in Zotero cause easykey error

### ISSUE THREAD

**Issue by scottmartincampbell** [egh/zotxt-emacs#5]
I was testing the easykey completion, and ran into a problem with duplicates in the Zotero library. It's possible to create/complete a key if a duplicate exists, but when trying to follow the easykey from emacs, zotxt throws the following error:

`REQUEST [error] Error (error) while connecting to http://127.0.0.1:23119/zotxt/select.`

Removing the duplicate solves the problem, but I can imagine that this might be a problem for very similar entries. 

Edit: In fact, I can confirm that similar entries end up with the same easykey, which then cause a collision. For example, the same auther, the same year, and the same title, but a different month end up with the same key.

**Comment by egh** [comment]
@scottmartincampbell Sorry, I'm working through my old tickets. I don't really know a way around this other than to use Better BibTex keys or to define a custom key by adding a tag starting with `@` to an item. Hope that helps!

**Comment by egh** [comment]
Oh, also, I'm going to work on improving the docs and support for Better BibTeX keys, which I think provide a better infrastructure for keys than easy keys going forward.

**Comment by egh** [comment]
I'm deprecating easy keys & recommending everybody use better bibtex, so I am going to close this ticket. Thank you for the report!
