### ISSUE TITLE
Nil entry from `org-zotxt-insert-reference-link`

### ISSUE THREAD

**Issue by alecshaw** [egh/zotxt-emacs#50]
When using `org-zotxt-insert-reference-link`, when I try to add an entry from Zotero, it appears in Emacs as `zotero://select/items/nil`, and the error message `[error] request--callback: peculiar error: 500` is printed.

zotxt appears to be working correctly up until the point of insertion, as it can pull up a list of matching entries, but when I select any one, this null link is produced. I'm not sure how to proceed to fix this; any input would be much appreciated.

Here is the Zotero debug output, in the hope that it may be useful.

```javascript
(5)(+0000002): HTTP/1.0 500 Internal Server Error X-Zotero-Version: 5.0.92 X-Zotero-Connector-API-Version: 2 Content-Type: text/plain; charset=UTF-8 csl is nullTypeError: csl is null buildBibliographyResponse/responseData<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/alecshaw/Library/Application%20Support/Zotero/Profiles/t2e64vee.default/extensions/zotxt@e6h.org.xpi!/bootstrap.js:220:9 buildBibliographyResponse@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/alecshaw/Library/Application%20Support/Zotero/Profiles/t2e64vee.default/extensions/zotxt@e6h.org.xpi!/bootstrap.js:219:24 buildResponse/<@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/alecshaw/Library/Application%20Support/Zotero/Profiles/t2e64vee.default/extensions/zotxt@e6h.org.xpi!/bootstrap.js:156:20 tryCatcher@resource://zotero/loader.jsm -> resource://zotero/bluebird/util.js:16:16 module.exports/Promise.prototype._settlePromiseFromHandler@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:512:13 module.exports/Promise.prototype._settlePromise@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:569:13 module.exports/Promise.prototype._settlePromise0@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:614:5 module.exports/Promise.prototype._settlePromises@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:693:13 module.exports/Promise.prototype._fulfill@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:638:13 module.exports/PromiseArray.prototype._resolve@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise_array.js:126:5 module.exports/MappingPromiseArray.prototype._promiseFulfilled@resource://zotero/loader.jsm -> resource://zotero/bluebird/map.js:101:13 module.exports/Promise.prototype._settlePromise@resource://zotero/loader.jsm -> resource://zotero/bluebird/promise.js:574:17 module.exports/Promis… (3541 chars)
```

zotxt 5.1.0
Zotero 5.0.92
zotxt-emacs 20200120.1950
GNU Emacs 27.1
macOS 10.15.7

**Comment by egh** [comment]
Thanks for the report! The problem is probably that `zotxt-default-bibliography-style` is set to something that isn't available for you in zotero. Sorry - it should report a better error message. Can you tell me what the value of `zotxt-default-bibliography-style` is? And if it's chicago (the default) can you check that you have that style installed in Zotero? Thanks!

**Comment by alecshaw** [comment]
Thank you for your reply!

This was exactly the issue. I removed the setting from my init file and it fixed the issue, and then I understood it was looking for a filename, not the name within Zotero. I had written the style name as it appears in Zotero, not as the `.cls` file is stored.

```lisp
(eval-after-load "zotxt"
  '(setq zotxt-default-bibliography-style "Unified style sheet for linguistics"))
```

Replacing the above with `unified-style-sheet-for-linguistics` makes everything work.

Many thanks for resolving the issue.

**Comment by egh** [comment]
Great! I'm working on a better error message for this so it should be more clear in the future.
