### ISSUE TITLE
Function `org-zotxt-update-reference-link-at-point` eats up spaces after the link

### ISSUE THREAD

**Issue by codetrick** [egh/zotxt-emacs#54]
emacs version: 27.1
zotxt-emacs version: 20210115.456

First, thanks for this very helpful package!

I found that the function will eat up spaces if the target link has spaces after it. I think it's because `(org-element-context)` returns the end position that is just before the next element / word. Fortunately there's a property `:post-blank` that we can use.

Proposed solution: 
Replace 
```elisp
                    (delete-region (org-element-property :begin ct)
                                   (org-element-property :end ct))

```
with 
```elisp
                    (delete-region (org-element-property :begin ct)
                                   (- (org-element-property :end ct)
                                      (org-element-property :post-blank ct)))
```

**Comment by egh** [comment]
This looks good to me! Can you file a pull request? Thanks.
