### ISSUE TITLE
`org-zotxt-noter` not loaded?

### ISSUE THREAD

**Issue by edgar-vincent** [egh/zotxt-emacs#58]
Hi!

Thanks a lot for this extremely useful package.

I installed `zotxt` in Doom Emacs, which uses `straight.el`, with `(package! zotxt)`. `org-noter` is also installed.
However, after enabling `org-zotxt-mode`, the `org-zotxt-noter` command doesn't seem to be defined. It works after I have `eval-defun`ed it from the source file.

I should probably be giving you more information about this, but I'm not quite sure what would be useful. I'm using the latest version of Doom Emacs with Emacs 27.1.

Thanks a lot!

EV

**Comment by egh** [comment]
Hi @edgar-vincent  - I'm not sure how straight works, but if you use `M-x load-library org-zotxt-noter` or `(require 'org-zotxt-noter)` that should do the trick. Or if you bind it to a key it should probably autoload.

**Comment by edgar-vincent** [comment]
Indeed, all your suggestions work. Sorry for my silly question - hopefully it'll help others :)

Thanks.
