### ISSUE TITLE
Search and select Zotero item

### ISSUE THREAD

**Issue by scottmartincampbell** [egh/zotxt-emacs#7]
It would be handy to be able to search Zotero from emacs and then jump to the item, rather than insert a link or reference. Sort of like how helm-bibtex searches a bib file, and is able to insert a reference or jump to the bibtex entry. 

I modified `org-zotxt-insert-reference-link` to create a custom function that can do this, but since it's a bit of a hack I thought I'd submit an official request.

**Comment by egh** [comment]
That sounds like a great idea, and like you say it should be really easy.

It might be nice as well to be able to jump to an attachment as well (similar to `org-zotxt-open-attachment`).

Do you have code you can share?

**Comment by egh** [comment]
I'm closing out some old tickets, but if you have a PR please do feel free to submit it or run it past me. Thank you!
