### ISSUE TITLE
emacs 25.1?

### ISSUE THREAD

**Issue by pierwill** [egh/zotxt-emacs#8]
Has emacs 25.1 broken org-zotxt for anyone else?

**Comment by egh** [comment]
Sorry, I was on vacation.

It works for me in emacs 26.0.50.2 (the emacs-snapshot PPA). Are you using melpa or melpa stable?

**Comment by pierwill** [comment]
nevermind, seems to have been a hiccup. not exactly sure what version i'm on

*sheepish*

**Comment by egh** [comment]
Cool, thanks for the update!
